tracker/config/routes.rb
Rails.application.routes.draw do

  resources :clients, only: [:index, :new, :create, :show, :edit, :update] do
    resources :projects, only: [:new, :create, :show, :edit, :update]
  end

  scope shallow_path: "proj" do
    resources :projects, only: [:none] do
      resources :deliverables, only: [:new, :create, :show, :edit, :update],shallow: true
    end
  end

  scope shallow_path: "del" do
    resources :deliverables, only: [:none] do
      resources :issues, only: [:new, :create, :show, :edit, :update],shallow: true
    end
  end

  get "sign_up" => "users#new", :as => "sign_up"

  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions

  resources :users

  root 'clients#index'

end

tracker/app/models/client.rb
class Client < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, format: { with: /[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})/}
	validates_uniqueness_of :email
	has_many :projects
end

tracker/app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
	belongs_to :project
	has_many :issues
end

tracker/app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :deliverable
end

tracker/app/models/project.rb
class Project < ActiveRecord::Base

	belongs_to :client
	has_many :deliverables
end

tracker/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def encrypt_password
	    if password.present?
	      self.password_salt = BCrypt::Engine.generate_salt
	      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	    end
  	end
	
	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
		  user
		else
		  nil
		end
	end
  
  	
	end

tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

tracker/app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients=Client.all 
  end
  
  def new
    if current_user
  	  @client=Client.new
    else
      flash[:notice] = 'You must be logged in to do that!'
      redirect_to root_url
    end

  end

  def create
  	@client=Client.new(client_params)
  	validate_new_client_form
  end

  def show
    @client = Client.find(params[:id])
    @projects=Project.all
  end 

  def edit
    if current_user
      @client = Client.find(params[:id])
    else
      flash[:notice] = 'You must be logged in to do that!'
      redirect_to root_url
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:notice] = 'Client successfully edited!'
      redirect_to root_url
    else
      render "edit"
    end

  end

  private

  def validate_new_client_form
  	if @client.save
  		flash[:notice] = 'Client successfully added!'
  		redirect_to root_url
  	else
  		render "new"
  	end
  end


  def client_params
    params.require(:client).permit(:first_name, :last_name, :company_name, :email)
  end
end

tracker/app/controllers/deliverables_controller.rb
class DeliverablesController < ApplicationController
	def new
		if current_user
		  	@project=Project.find(params[:project_id])
		  	@deliverable=Deliverable.new
	  	else
	      flash[:notice] = 'You must be logged in to do that!'
	      redirect_to root_url
    	end
	end

	def create
		@project=Project.find(params[:project_id])
  		@deliverable=@project.deliverables.create(deliverable_params)
  		redirect_to root_url

	end

	def show
	  	@deliverable=Deliverable.find(params[:id])
	end

	def edit
		if current_user
	  	@deliverable=Deliverable.find(params[:id])
	  	puts @deliverable.inspect
		else
	      flash[:notice] = 'You must be logged in to do that!'
	      redirect_to root_url
	    end
	end

	def update
	    @deliverable = Deliverable.find(params[:id])
	    if @deliverable.update(deliverable_params)
	      flash[:notice] = 'deliverable successfully edited!'
	      redirect_to deliverable_path(@deliverable)
	    else
	      render "edit"
	    end
	end

	private

	def validate_new_deliverable_form
		if @deliverable.save
			flash[:notice] = 'Deliverable successfully added!'
			redirect_to root_url
		else
			render "new"
		end
	end


	def deliverable_params
		params.require(:deliverable).permit(:name, :description)
	end

end

tracker/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	def new
		if current_user
			@deliverable=Deliverable.find(params[:deliverable_id])
		  	@issue=Issue.new
		else
	      flash[:notice] = 'You must be logged in to do that!'
	      redirect_to root_url
	    end
	end

	def create
		@deliverable=Deliverable.find(params[:deliverable_id])
  		@issue=@deliverable.issues.create(issue_params)
  		redirect_to root_url
	end

	def show
	  	@issue=Issue.find(params[:id])
	end

	def edit
		if current_user
	  		@issue=Issue.find(params[:id])
	  	else
	      flash[:notice] = 'You must be logged in to do that!'
	      redirect_to root_url
	    end
	end

	def update
	    @issue = Issue.find(params[:id])
	    if @issue.update(issue_params)
	      flash[:notice] = 'issue successfully edited!'
	      redirect_to issue_path(@issue)
	    else
	      render "edit"
	    end
	end

	private

	def validate_new_issue_form
		if @issue.save
			flash[:notice] = 'Issue successfully added!'
			redirect_to root_url
		else
			render "new"
		end
	end


	def issue_params
		params.require(:issue).permit(:title, :body, :budgeted_time, :priority)
	end
end

tracker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def new
    if current_user
    	@client=Client.find(params[:client_id])
    	@project=Project.new
    else
      flash[:notice] = 'You must be logged in to do that!'
      redirect_to root_url
    end
  end

  def create
  	@client=Client.find(params[:client_id])
  	@project=@client.projects.create(project_params)
  	redirect_to client_path(@client)
  end

  def show
  	@client=Client.find(params[:client_id])
  	@project=@client.projects.find(params[:id])
  end
  
  def edit
    if current_user
    	@client=Client.find(params[:client_id])
    	@project=@client.projects.find(params[:id])
    else
      flash[:notice] = 'You must be logged in to do that!'
      redirect_to root_url
    end
  end

  def update
    @client = Client.find(params[:client_id])
    @project=@client.projects.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = 'project successfully edited!'
      redirect_to client_project_path(@client,@project)
    else
      render "edit"
    end

  end

  private

  def validate_new_project_form
  	if @project.save
  		flash[:notice] = 'Project successfully added!'
  		redirect_to root_url
  	else
  		render "new"
  	end
  end


  def project_params
    params.require(:project).permit(:name, :description)
  end
end

tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user=User.new(user_params)
  	if @user.save
  		redirect_to root_url, :notice => "Signed Up!"
  	else
  		render "new"
  	end
  end

  private 

  def user_params
	params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  end
end

tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

tracker/app/helpers/clients_helper.rb
module ClientsHelper
end

tracker/app/helpers/deliverables_helper.rb
module DeliverablesHelper
end

tracker/app/helpers/issues_helper.rb
module IssuesHelper
end

tracker/app/helpers/projects_helper.rb
module ProjectsHelper
end

tracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

tracker/app/helpers/users_helper.rb
module UsersHelper
end

tracker/app/views/clients/edit.html.erb
<h1>Edit <%= "#{@client.first_name} #{@client.last_name}"%></h1>

<%= form_for :client, url: client_path(@client), method: :patch do |f| %>

	<% if @client.errors.any? %>
	    <ul>
	    <% @client.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<%= f.label :first_name, "First Name:" %>
	<%= f.text_field :first_name %><br />

	<%= f.label :last_name, "Last Name:" %>
	<%= f.text_field :last_name %><br />

	<%= f.label :company_name, "Company Name:"%>
	<%= f.text_field :company_name %><br />

	<%= f.label :email, "Email:" %>
	<%= f.text_field :email %><br />

	<%= f.submit %>	
<% end %>
 
<%= link_to 'Back', clients_path %>

tracker/app/views/clients/index.html.erb
<h1>Clients</h1>
<%if current_user %>

	<h2><%= link_to 'Add Client', new_client_path(@client) %></h2>

<%end%>

 <% flash.each do |name,msg| %>
    <%= msg %></br>
 <% end %>

<ul>
	<% @clients.each do |client| %>
		<li>
			<tr>
				<h3><td><%="#{client.first_name} #{client.last_name} "%></td></h3>
				<td><%="#{client.email} "%></td>
				<td><%="#{client.company_name} "%></td>
				
				<td><%= link_to ' Client Details & Projects', client_path(client) %></td>
				<%if current_user %>
		    		<td><%= link_to ' Edit Client', edit_client_path(client) %></td>

		    	<%end%>
			</tr>
		</li>
	<%end%>
</ul>

tracker/app/views/clients/new.html.erb
<h1>Add a new client</h1>

<% if @client.errors.any? %>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @client do |f| %>
  <%= f.label :first_name, "First Name:" %>
  <%= f.text_field :first_name %><br />

  <%= f.label :last_name, "Last Name:" %>
  <%= f.text_field :last_name %><br />

  <%= f.label :company_name, "Company Name:"%>
  <%= f.text_field :company_name %><br />

  <%= f.label :email, "Email:" %>
  <%= f.text_field :email %><br />
  <%= f.submit %>
<% end %>

tracker/app/views/clients/show.html.erb
<h1><%="Here are the Client Details about #{@client.first_name} #{@client.last_name}"%></h1>

<p><%=@client.company_name%></p>
<p><%=@client.email%></p>

<%= link_to 'Back', clients_path %>
<%if current_user %>
	<%= link_to 'Edit', edit_client_path(@client) %>
	<%= link_to 'New Project', new_client_project_path(@client) %>
<%end%>

<h2>Projects</h2>

<ul>
	<% @client.projects.each do |project| %>
		<li>
			<tr>
				<td><%="#{project.name} "%></td>
				<td><%="#{project.description} "%></td>
				<td><%= link_to ' Project Details', client_project_path(@client,project)%></td>
				<%if current_user %>
		    		<td><%= link_to ' Edit Project', edit_client_project_path(@client,project)%></td>
	    		<%end%>

			</tr>
		</li>	
	<%end%>
</ul>

tracker/app/views/deliverables/edit.html.erb
<h1>Edit Deliverable</h1>

<h1><%= "#{@deliverable.name}"%></h1>

<%= form_for :deliverable, url: deliverable_path(@deliverable), method: :patch do |f| %>

	<% if @deliverable.errors.any? %>
	    <ul>
	    <% @deliverable.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<%= f.label :name, "Name:" %>
	<%= f.text_field :name %><br />

	<%= f.label :description, "Description:" %>
	<%= f.text_field :description %><br />

	<%= f.submit %>	
<% end %>
 
<%= link_to 'Back', deliverable_path %>

tracker/app/views/deliverables/new.html.erb
<h1>Add a new deliverable for <%=" #{@project.name}"%></h1>


<% if @deliverable.errors.any? %>
    <ul>
    <% @deliverable.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@project,@deliverable] do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %><br />

  <%= f.label :description, "Description:" %>
  <%= f.text_field :description %><br />

  <%= f.submit %>
  
<% end %>

tracker/app/views/deliverables/show.html.erb
<h2><%="Deliverable: #{@deliverable.name}"%></h2>

<p><%=@deliverable.description%><p>


<%= link_to ' Go Back', :back%>
<%= link_to ' Go Home', root_path%>
<%if current_user %>
	<%= link_to ' Edit deliverable', edit_deliverable_path(@deliverable)%>
	<%= link_to ' Add Issue', new_deliverable_issue_path(@deliverable)%>
<%end%>


<h2>Issues</h2>


<ul>
	<% @deliverable.issues.each do |issue| %>
		<li>
			<tr>
				<td><%="#{issue.title} "%></td>
				<td><%="#{issue.priority} "%></td>
				<td><%="#{issue.budgeted_time} "%></td>
				<td><%= link_to ' Issue Details', issue_path(issue)%></td>
				<%if current_user %>
		    		<td><%= link_to ' Edit Issue', edit_issue_path(issue)%></td>
	    		<%end%>



			</tr>
		</li>	
	<%end%>
</ul>

tracker/app/views/issues/edit.html.erb
<h1>Edit Issue</h1>

<h1><%= "#{@issue.title}"%></h1>

<%= form_for :issue, url: issue_path(@issue), method: :patch do |f| %>

	<% if @issue.errors.any? %>
	    <ul>
	    <% @issue.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<%= f.label :title, "Issue Title Name:" %>
	<%= f.text_field :title %><br />

	<%= f.label :body, "Body:" %>
	<%= f.text_field :body %><br />

	<%= f.label :budgeted_time, "Budgeted time:" %>
	<%= f.text_field :budgeted_time %><br />

	<%= f.label :priority, "Priority:" %>
	<%= f.text_field :priority %><br />

	<%= f.submit %>	
<% end %>
 
<%= link_to 'Back', issue_path %>

tracker/app/views/issues/new.html.erb
<h1>Add a new issue for <%=" #{@deliverable.name}"%></h1>


<% if @issue.errors.any? %>
    <ul>
    <% @issue.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@deliverable,@issue] do |f| %>
  <%= f.label :title, "Issue Title Name:" %>
  <%= f.text_field :title %><br />

  <%= f.label :body, "Body:" %>
  <%= f.text_field :body %><br />
  
  <%= f.label :budgeted_time, "Budgeted time:" %>
  <%= f.text_field :budgeted_time %><br />
  
  <%= f.label :priority, "Priority:" %>
  <%= f.text_field :priority %><br />

  <%= f.submit %>
  
<% end %>

tracker/app/views/issues/show.html.erb
<h2><%="Issue: #{@issue.title}"%></h2>

<p><%=@issue.body%><p>

<%if current_user %>
	<%= link_to ' Edit issue', edit_issue_path(@issue)%>
<%end%>
<%= link_to ' Go Back', :back%>
<%= link_to ' Go Home', root_path%>

tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

tracker/app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<h1>Edit <%= "#{@project.name}"%></h1>

<%= form_for :project, url: client_project_path(@client,@project), method: :patch do |f| %>

	<% if @project.errors.any? %>
	    <ul>
	    <% @project.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<%= f.label :name, "Name:" %>
	<%= f.text_field :name %><br />

	<%= f.label :description, "Description:" %>
	<%= f.text_field :description %><br />


	<%= f.submit %>	
<% end %>
 
<%= link_to 'Back', clients_path %>

tracker/app/views/projects/new.html.erb
<h1>Add a new project for <%="#{@client.first_name} #{@client.last_name}"%></h1>


<% if @project.errors.any? %>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@client,@project] do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %><br />

  <%= f.label :description, "Description:" %>
  <%= f.text_field :description %><br />

  <%= f.submit %>
  
<% end %>

tracker/app/views/projects/show.html.erb
<h2><%="PROJECT: #{@project.name}"%></h2>

<p><%=@project.description%><p>

<%= link_to 'Back to Client', clients_path %>
<%if current_user %>
	<%= link_to ' Edit Project', edit_client_project_path(@client,@project)%>
	<%= link_to ' Add Deliverable', new_project_deliverable_path(@project)%>
<%end%>

<h2>Deliverables</h2>

<ul>
	<% @project.deliverables.each do |deliverable| %>
		<li>
			<tr>
				<td><%="#{deliverable.name} "%></td>
				<td><%="#{deliverable.description} "%></td>
				<td><%= link_to ' Deliverable Details', deliverable_path(deliverable)%></td>
				<%if current_user %>
		    		<td><%= link_to ' Edit Deliverables', edit_deliverable_path(deliverable)%></td>
	    		<%end%>

			</tr>
		</li>	
	<%end%>
</ul>

tracker/app/views/users/new.html.erb
<h1>Sign Up</h1>


<%=form_for @user do |f|%>
	<% if @user.errors.any? %>
		<div class="error_messages">
		  <h2>Form is invalid</h2>
		  <ul>
		    <% for message in @user.errors.full_messages %>
		      <li><%= message %></li>
		    <% end %>
		  </ul>
		</div>
	<% end %>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</p>
	<p>
	<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>	
	</p>

	<p class="button"><%= f.submit %></p>
<% end %>